/**
 * AIP airspace overlay - src/lib/airspace.js (v16.31)
 *
 * The pure half of roadmap item 4: which airspaces to draw for a given
 * viewport, how to colour them, and what to say about one on hover. The
 * Leaflet layers themselves live in the page, with the rest of the map code.
 *
 * DATA: `window.C182_AIP`, generated by tools/build-aip.mjs from the official
 * Avinor eAIP and inlined into both deliveries at the @AIPDATA marker (a
 * file:// page can neither fetch() nor load an ES module). Airspace data is
 * used with permission from Avinor AS, NON-COMMERCIALLY; the national border
 * within it is Kartverket, NLOD. See CLAUDE.md - the non-commercial condition
 * binds the whole project.
 *
 * WHY CULLING IS NOT OPTIONAL: the dataset holds 228 volumes covering all of
 * Norway. Handing every one to Leaflet makes panning unusable, and at country
 * zoom the result is an unreadable wash that hides the CTRs and TMAs a VFR
 * pilot actually needs. So: nothing below MIN_ZOOM, and only what intersects
 * the viewport.
 *
 * WHY HOVER AND NOT CLICK: a click on the map adds a waypoint, and airspace
 * covers most of the map. Making the polygons take clicks would break route
 * building everywhere inside a TMA. Hover carries the information; the click
 * falls through to the map untouched.
 *
 * Pure: no DOM, no Leaflet. The page passes the viewport in and gets plain
 * data back.
 */

/** Nothing is drawn below this zoom: at country zoom 228 polygons are a wash
 *  that buries the airspace that matters. */
export const AIRSPACE_MIN_ZOOM = 7;

/**
 * How each kind is drawn. The fill is deliberately very light - the point of
 * the ICAO chart underneath is that you can read it, and an overlay that
 * obscures the terrain, the MEF figures or the frequencies has made the
 * planner worse.
 *
 * @type {Record<string, {label: string, color: string, dash: string|null}>}
 */
export const AIRSPACE_STYLES = {
  CTR:     { label: 'Control zone',            color: '#2b6cb0', dash: null },
  TIZ:     { label: 'Traffic information zone', color: '#2f855a', dash: null },
  TMA:     { label: 'Terminal control area',   color: '#6b46c1', dash: '6,4' },
  TIA:     { label: 'Traffic information area', color: '#0987a0', dash: '6,4' },
  CTA:     { label: 'Control area',            color: '#4a5568', dash: '2,5' },
  RMZ:     { label: 'Radio mandatory zone',    color: '#c05621', dash: '8,4' },
  TMZ:     { label: 'Transponder mandatory zone', color: '#c05621', dash: '8,4' },
  RMZ_TMZ: { label: 'Radio + transponder mandatory zone', color: '#c05621', dash: '8,4' },
  HTZ:     { label: 'Helicopter traffic zone', color: '#975a16', dash: null },
  ADS:     { label: 'Advisory area',           color: '#975a16', dash: '2,5' }
};

const DEFAULT_STYLE = { label: 'Airspace', color: '#718096', dash: '4,4' };

/** @param {string} kind @returns {{label: string, color: string, dash: string|null}} */
export function airspaceStyle(kind) {
  return AIRSPACE_STYLES[String(kind || '').toUpperCase()] || DEFAULT_STYLE;
}

/**
 * The bounding box of a feature's ring, computed once and cached on it.
 *
 * @param {AirspaceFeature} f
 * @returns {{south: number, west: number, north: number, east: number}}
 */
export function airspaceBounds(f) {
  if (f._bbox) return f._bbox;
  let south = 90, north = -90, west = 180, east = -180;
  for (const [lat, lng] of f.ring) {
    if (lat < south) south = lat;
    if (lat > north) north = lat;
    if (lng < west) west = lng;
    if (lng > east) east = lng;
  }
  f._bbox = { south, west, north, east };
  return f._bbox;
}

/**
 * Which airspaces to draw right now.
 *
 * @param {AirspaceFeature[]} features
 * @param {{south: number, west: number, north: number, east: number}} view
 * @param {number} zoom
 * @param {{kinds?: Record<string, boolean>, minZoom?: number}} [opts]
 *   `kinds` omitted means every kind; a kind mapped to false is hidden.
 * @returns {AirspaceFeature[]}
 */
export function visibleAirspaces(features, view, zoom, opts) {
  const minZoom = opts && typeof opts.minZoom === 'number' ? opts.minZoom : AIRSPACE_MIN_ZOOM;
  if (!(zoom >= minZoom)) return [];
  const kinds = opts && opts.kinds;
  /** @type {AirspaceFeature[]} */
  const out = [];
  for (const f of features || []) {
    if (kinds && kinds[f.kind] === false) continue;
    const b = airspaceBounds(f);
    // bbox overlap; a polygon larger than the viewport still overlaps it
    if (b.south > view.north || b.north < view.south) continue;
    if (b.west > view.east || b.east < view.west) continue;
    out.push(f);
  }
  // Draw the biggest first so a CTR inside a TMA stays clickable-through and
  // visually on top rather than buried under the larger wash.
  out.sort((a, b) => bboxArea(b) - bboxArea(a));
  return out;
}

/** @param {AirspaceFeature} f @returns {number} */
function bboxArea(f) {
  const b = airspaceBounds(f);
  return (b.north - b.south) * (b.east - b.west);
}

/**
 * The published vertical band, as text.
 *
 * NEVER recomputed from a number: the importer keeps GND / UNL / FL as the
 * codes they are, and this only joins what was published. A missing limit
 * shows as `?` rather than being filled in with a plausible altitude.
 *
 * @param {AirspaceFeature} f @returns {string}
 */
export function limitsText(f) {
  const lo = (f.lower && f.lower.text) || '?';
  const hi = (f.upper && f.upper.text) || '?';
  return `${lo} – ${hi}`;
}

/**
 * The civil VHF air band. A published airspace block often carries military
 * UHF alongside the VHF - Bardufoss CTR lists twelve frequencies including
 * 243.000 (guard), 257.800, 280.700 and 397.375 - and a hover card that
 * recites all of them buries the one a C182 would actually call on.
 *
 * NOTHING IS DISCARDED: every published frequency stays in `data/aip.js`, and
 * the card says how many it is not showing. This is a display decision, not a
 * data decision, and the AIP remains the reference.
 */
export const VHF_MIN_MHZ = 118;
export const VHF_MAX_MHZ = 137;

/** @param {{mhz: string}[]} freqs @returns {{vhf: string[], others: number}} */
export function splitFrequencies(freqs) {
  /** @type {string[]} */
  const vhf = [];
  let others = 0;
  for (const q of freqs || []) {
    const n = Number(String(q && q.mhz).trim());
    if (!isFinite(n)) { continue; }
    if (n >= VHF_MIN_MHZ && n < VHF_MAX_MHZ) vhf.push(q.mhz);
    else others++;
  }
  return { vhf, others };
}

/**
 * What hovering an airspace says. Plain text lines; the page wraps them.
 *
 * Order is what a pilot needs first: what it is, how high, what class, who to
 * call. The frequency is the reason this feature exists - reading a TMA's
 * boundary off the chart is easy, remembering its approach frequency is not.
 *
 * @param {AirspaceFeature} f
 * @returns {{title: string, lines: string[]}}
 */
export function airspaceInfo(f) {
  const style = airspaceStyle(f.kind);
  const lines = [];
  lines.push(style.label + (f.class ? ` · Class ${f.class}` : ' · class not published'));
  lines.push(limitsText(f));
  for (const cs of f.callsigns || []) lines.push(cs);
  const { vhf, others } = splitFrequencies(f.freqs);
  if (vhf.length) {
    lines.push(vhf.join('  ') + ' MHz' + (others ? `  (+${others} non-VHF, see AIP)` : ''));
  } else if (others) {
    lines.push(`${others} published frequency(ies), none in the VHF band - see AIP`);
  }
  // A resolved national border is worth stating: the shape came from
  // Kartverket, not from the AIP's own coordinate list.
  if (f.borderSegments) {
    lines.push(`boundary follows the national border (Kartverket)`);
  }
  return { title: f.name, lines };
}

/**
 * The attribution the overlay must display whenever it is on. Both grants are
 * named because both are load-bearing and they are different: the AIP is used
 * by permission and non-commercially, the border is open data.
 *
 * @param {{attribution?: string, editionLabel?: string, effectiveFrom?: string}|null} dataset
 * @returns {string}
 */
export function airspaceAttribution(dataset) {
  if (!dataset) return '';
  const edition = dataset.editionLabel ? ` ${dataset.editionLabel}` : '';
  const eff = dataset.effectiveFrom ? `, effective ${dataset.effectiveFrom}` : '';
  return `Airspace: AIP Norge${edition}${eff} — © Avinor, used with permission, ` +
    `non-commercial. National border © Kartverket (NLOD). ` +
    `Not for navigation; verify against the current AIP and NOTAM.`;
}

/**
 * Every kind present in a dataset, with a count, for the layer control.
 * @param {AirspaceFeature[]} features
 * @returns {{kind: string, label: string, count: number}[]}
 */
export function airspaceKinds(features) {
  /** @type {Record<string, number>} */
  const counts = {};
  for (const f of features || []) counts[f.kind] = (counts[f.kind] || 0) + 1;
  return Object.keys(counts).sort().map((kind) => ({
    kind, label: airspaceStyle(kind).label, count: counts[kind]
  }));
}
