/**
 * AIP airspace overlay - src/lib/airspace.js (v16.31, sectors v16.33)
 *
 * The pure half of roadmap item 4: which airspaces to draw for a given
 * viewport, how to colour them, and what to say about one on hover. The
 * Leaflet layers themselves live in the page, with the rest of the map code.
 *
 * DATA: `window.C182_AIP`, generated by tools/build-aip.mjs from the official
 * Avinor eAIP and inlined into both deliveries at the @AIPDATA marker (a
 * file:// page can neither fetch() nor load an ES module). Airspace data is
 * used with permission from Avinor AS, NON-COMMERCIALLY; the national border
 * within it is Kartverket, NLOD. See CLAUDE.md - the non-commercial condition
 * binds the whole project.
 *
 * WHY CULLING IS NOT OPTIONAL: the dataset holds 228 volumes covering all of
 * Norway. Handing every one to Leaflet makes panning unusable, and at country
 * zoom the result is an unreadable wash that hides the CTRs and TMAs a VFR
 * pilot actually needs. So: nothing below MIN_ZOOM, and only what intersects
 * the viewport.
 *
 * WHY HOVER AND NOT CLICK: a click on the map adds a waypoint, and airspace
 * covers most of the map. Making the polygons take clicks would break route
 * building everywhere inside a TMA. Hover carries the information; the click
 * falls through to the map untouched.
 *
 * Pure: no DOM, no Leaflet. The page passes the viewport in and gets plain
 * data back.
 */

/** Nothing is drawn below this zoom: at country zoom 228 polygons are a wash
 *  that buries the airspace that matters. */
export const AIRSPACE_MIN_ZOOM = 7;

/**
 * How each kind is drawn. The fill is deliberately very light - the point of
 * the ICAO chart underneath is that you can read it, and an overlay that
 * obscures the terrain, the MEF figures or the frequencies has made the
 * planner worse.
 *
 * @type {Record<string, {label: string, color: string, dash: string|null}>}
 */
export const AIRSPACE_STYLES = {
  CTR:     { label: 'Control zone',            color: '#2b6cb0', dash: null },
  TIZ:     { label: 'Traffic information zone', color: '#2f855a', dash: null },
  TMA:     { label: 'Terminal control area',   color: '#6b46c1', dash: '6,4' },
  TIA:     { label: 'Traffic information area', color: '#0987a0', dash: '6,4' },
  CTA:     { label: 'Control area',            color: '#4a5568', dash: '2,5' },
  RMZ:     { label: 'Radio mandatory zone',    color: '#c05621', dash: '8,4' },
  TMZ:     { label: 'Transponder mandatory zone', color: '#c05621', dash: '8,4' },
  RMZ_TMZ: { label: 'Radio + transponder mandatory zone', color: '#c05621', dash: '8,4' },
  HTZ:     { label: 'Helicopter traffic zone', color: '#975a16', dash: null },
  ADS:     { label: 'Advisory area',           color: '#975a16', dash: '2,5' }
};

const DEFAULT_STYLE = { label: 'Airspace', color: '#718096', dash: '4,4' };

/** @param {string} kind @returns {{label: string, color: string, dash: string|null}} */
export function airspaceStyle(kind) {
  return AIRSPACE_STYLES[String(kind || '').toUpperCase()] || DEFAULT_STYLE;
}

/**
 * The bounding box of a feature's ring, computed once and cached on it.
 *
 * @param {AirspaceFeature} f
 * @returns {{south: number, west: number, north: number, east: number}}
 */
export function airspaceBounds(f) {
  if (f._bbox) return f._bbox;
  let south = 90, north = -90, west = 180, east = -180;
  for (const [lat, lng] of f.ring) {
    if (lat < south) south = lat;
    if (lat > north) north = lat;
    if (lng < west) west = lng;
    if (lng > east) east = lng;
  }
  f._bbox = { south, west, north, east };
  return f._bbox;
}

/**
 * Which airspaces to draw right now.
 *
 * @param {AirspaceFeature[]} features
 * @param {{south: number, west: number, north: number, east: number}} view
 * @param {number} zoom
 * @param {{kinds?: Record<string, boolean>, minZoom?: number}} [opts]
 *   `kinds` omitted means every kind; a kind mapped to false is hidden.
 * @returns {AirspaceFeature[]}
 */
export function visibleAirspaces(features, view, zoom, opts) {
  const minZoom = opts && typeof opts.minZoom === 'number' ? opts.minZoom : AIRSPACE_MIN_ZOOM;
  if (!(zoom >= minZoom)) return [];
  const kinds = opts && opts.kinds;
  /** @type {AirspaceFeature[]} */
  const out = [];
  for (const f of features || []) {
    if (kinds && kinds[f.kind] === false) continue;
    const b = airspaceBounds(f);
    // bbox overlap; a polygon larger than the viewport still overlaps it
    if (b.south > view.north || b.north < view.south) continue;
    if (b.west > view.east || b.east < view.west) continue;
    out.push(f);
  }
  // Draw the biggest first so a CTR inside a TMA stays clickable-through and
  // visually on top rather than buried under the larger wash.
  out.sort((a, b) => bboxArea(b) - bboxArea(a));
  return out;
}

/** @param {AirspaceFeature} f @returns {number} */
function bboxArea(f) {
  const b = airspaceBounds(f);
  return (b.north - b.south) * (b.east - b.west);
}

/**
 * The published vertical band, as text.
 *
 * NEVER recomputed from a number: the importer keeps GND / UNL / FL as the
 * codes they are, and this only joins what was published. A missing limit
 * shows as `?` rather than being filled in with a plausible altitude.
 *
 * @param {AirspaceFeature} f @returns {string}
 */
export function limitsText(f) {
  const lo = (f.lower && f.lower.text) || '?';
  const hi = (f.upper && f.upper.text) || '?';
  return `${lo} – ${hi}`;
}

/**
 * WHICH FREQUENCIES A VFR PILOT ACTUALLY WANTS, and why the rest are hidden.
 *
 * A published airspace block carries every ATS frequency the aerodrome has.
 * Bardufoss CTR lists twelve, and reciting all twelve buries the three that
 * matter. Shown: ATIS, Approach, Tower, and AFIS (the "Information" service
 * at an AFIS field). Hidden: clearance delivery, surface movement, en-route
 * ACC sectors and non-ATS radio stations - a C182 planning a VFR flight is
 * not calling those.
 *
 * NOTHING IS DISCARDED FROM THE DATA. Every published service and frequency
 * stays in `data/aip.js`; this is the display filter and the AIP remains the
 * reference. There is deliberately no "+N hidden" remark - it was noise.
 */
export const SHOWN_SERVICES = ['ATIS', 'APP', 'TWR', 'AFIS'];

/**
 * Shown ONLY when an airspace has none of the above.
 *
 * Some TMAs have no local approach unit at all - Hammerfest, Helgeland and
 * Lofoten TMA are worked by Polaris Control, and Salen TMA by Salen Control.
 * Hiding the area-control frequency there would leave the card with no one to
 * call for a piece of CONTROLLED airspace, which is worse than one extra row.
 * A CTR that already has TWR and APP never gains a Polaris row.
 */
export const FALLBACK_SERVICES = ['ACC', 'RADIO', 'TFC'];

/** Human tag per service code. @type {Record<string, string>} */
const SERVICE_TAGS = {
  ATIS: 'ATIS', APP: 'APP', TWR: 'TWR', AFIS: 'AFIS',
  ACC: 'ACC', RADIO: 'RADIO', TFC: 'TFC'
};

/**
 * The civil VHF air band, and the reason it - not the source's `MIL` flag -
 * is what keeps military channels out.
 *
 * The eAIP marks SOME military frequencies with a `MIL` remark, but only six
 * in the whole edition: Bardufoss TWR publishes 243.000 with no marker at all.
 * So the band is the real filter (military air is UHF, 225-400 MHz) and the
 * MIL flag is applied on top to catch a military VHF channel.
 */
export const VHF_MIN_MHZ = 118;
export const VHF_MAX_MHZ = 137;

/**
 * Emergency frequencies. Never listed as a working frequency: every pilot
 * knows 121.500, it appears under almost every service, and printing it four
 * times per card crowds out the ones you actually need to dial.
 */
export const GUARD_MHZ = ['121.500', '243.000'];

/** @param {{mhz: string, remarks?: string}} q @returns {boolean} */
export function isUsableFrequency(q) {
  const n = Number(String((q && q.mhz) || '').trim());
  if (!isFinite(n)) return false;
  if (n < VHF_MIN_MHZ || n >= VHF_MAX_MHZ) return false;          // UHF military
  if (/\bMIL\b/i.test(String((q && q.remarks) || ''))) return false;  // flagged military
  if (GUARD_MHZ.includes(String(q.mhz).trim())) return false;      // guard
  return true;
}

/**
 * Is a point inside a ring? Ray casting, on lat/lng directly.
 *
 * Good enough because the rings here are small relative to the globe and the
 * question is only "which published sector is the cursor in" - it is never
 * used for a distance, a track or a fuel figure. A vertex-exact answer on the
 * boundary is not needed either: two adjacent sectors both claiming the seam
 * would simply show two rows, which is what a seam means anyway.
 *
 * @param {[number, number][]} ring @param {[number, number]} at
 * @returns {boolean}
 */
export function pointInRing(ring, at) {
  if (!ring || ring.length < 3 || !at) return false;
  const lat = at[0], lng = at[1];
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const yi = ring[i][0], xi = ring[i][1], yj = ring[j][0], xj = ring[j][1];
    if (((yi > lat) !== (yj > lat)) && (lng < (xj - xi) * (lat - yi) / (yj - yi) + xi)) {
      inside = !inside;
    }
  }
  return inside;
}

/**
 * Rough altitude for ORDERING sector rows only.
 *
 * Deliberately never used to decide whether a sector applies - that would mean
 * comparing a flight level against an altitude AMSL, which needs a QNH the
 * planner does not have. It only puts the lower band first, because a C182
 * reads the bottom of the stack. A wrong order is untidy; a wrong exclusion
 * would hide the frequency the pilot needs.
 *
 * @param {{ft: number|null, text: string, kind?: string}|null} lim
 * @returns {number}
 */
function orderingFt(lim) {
  if (!lim) return 0;
  if (typeof lim.ft === 'number') return lim.ft;
  const fl = /FL\s*(\d+)/i.exec(String(lim.text || ''));
  if (fl) return Number(fl[1]) * 100;
  if (/UNL/i.test(String(lim.text || ''))) return Infinity;
  return 0;
}

/**
 * The published ACC sectors containing a point, lowest band first.
 *
 * @param {AirspaceSector[]} sectors @param {[number, number]|null} at
 * @returns {AirspaceSector[]}
 */
export function sectorsAt(sectors, at) {
  if (!at || !sectors) return [];
  return sectors.filter((s) => pointInRing(s.ring, at))
    .slice()
    .sort((a, b) => orderingFt(a.lower) - orderingFt(b.lower));
}

/** The sector designator as it is worth printing: "Polaris ACC Sector 26" is
 *  "Sector 26" once the card already says Polaris Control.
 *  @param {AirspaceSector} s @returns {string} */
export function sectorLabel(s) {
  return String((s && s.name) || '').replace(/^.*\bACC\s+/i, '').trim() || String((s && s.name) || '');
}

/**
 * WHY THE AREA-CONTROL ROW NEEDS THE CURSOR POSITION.
 *
 * Polaris CTA is ONE airspace covering the whole country, so its published
 * block lists every Polaris sector frequency there is - 26 of them on the VHF
 * band alone. Reciting all 26 tells a pilot planning past Sorkjosen nothing:
 * the answer they need is the ONE sector that works that piece of sky.
 *
 * ENR 2.2 publishes each sector as its own airspace with its own lateral
 * boundary, so the sector under the cursor is a lookup, not a guess.
 *
 * AND THE GEOMETRY IS ONLY ALLOWED TO SELECT, NEVER TO ASSERT. A resolved
 * sector's frequency is shown only if it also appears in the hovered
 * airspace's OWN published frequency list - so the card can never state
 * something that airspace does not itself state. Measured over a grid of
 * every point inside a Polaris CTA volume: 1648 of 1648 sector hits were
 * corroborated that way, and the same lookup reproduces the AIP's own
 * per-airspace pairing at 24 of the 31 airspaces that publish exactly one
 * sector frequency (the other 7 are vertical stacks and multi-part airspaces
 * whose own pairing wins anyway, because it is only ever consulted when the
 * airspace lists MORE than one).
 *
 * When nothing resolves - over the Oslofjord, where Sectors 3 and 4 could not
 * be drawn because their boundary follows the MARITIME Norway-Sweden line
 * that Kartverket's land-border dataset does not contain - the card says so
 * and shows no frequency. Listing 26 would be worse than saying "look it up".
 *
 * @param {AirspaceFeature} f
 * @param {{sectors?: AirspaceSector[], at?: [number, number]|null}} [opts]
 * @returns {{rows: {tag: string, freqs: string[], callsign: string|null}[], note: string|null}}
 */
function accSectorRows(f, opts) {
  /** @type {{mhz: string, remarks?: string}[]} */
  const usable = [];
  /** @type {string|null} */
  let callsign = null;
  for (const sv of f.services || []) {
    if ((sv.code || '').toUpperCase() !== 'ACC') continue;
    if (!callsign && sv.callsign) callsign = sv.callsign;
    for (const q of sv.freqs || []) if (isUsableFrequency(q)) usable.push(q);
  }
  const mhz = [...new Set(usable.map((q) => q.mhz))];
  // One frequency: the airspace's own block already answers the question, and
  // no geometry is consulted. This is the normal case - Sorkjosen TIA and
  // Hammerfest TMA each publish exactly their own sector.
  if (mhz.length <= 1) return { rows: [], note: null };

  // No cursor position yet - the tooltip's initial content, bound before the
  // pointer has entered the polygon. Say what the card is waiting for rather
  // than claiming the sector is missing, which is a different thing entirely.
  const at = (opts && opts.at) || null;
  if (!at) {
    return { rows: [], note: 'area control frequency depends on the position within this airspace' };
  }

  const hits = sectorsAt((opts && opts.sectors) || [], at);
  const published = new Set(mhz);
  /** @type {{tag: string, freqs: string[], callsign: string|null}[]} */
  const rows = [];
  const seen = new Set();
  /** @type {string[]} */
  const notes = [];
  for (const s of hits) {
    if (!published.has(s.mhz) || seen.has(s.mhz)) continue;   // selector, not source
    seen.add(s.mhz);
    const band = hits.length > 1 && s.lower && s.upper ? ` (${s.lower.text} – ${s.upper.text})` : '';
    rows.push({
      tag: 'ACC',
      freqs: [s.mhz],
      callsign: `${callsign || 'Area control'} · ${sectorLabel(s)}${band}`
    });
    if (s.note && !notes.includes(s.note)) notes.push(s.note);
  }
  if (!rows.length) {
    return {
      rows: [],
      note: `${mhz.length} sector frequencies published here and the sector for this ` +
        `position is not in the dataset — see AIP ENR 2.2.`
    };
  }
  return { rows, note: notes.length ? notes.join(' ') : null };
}

/**
 * The service rows for the hover card: tag, frequencies, who you are calling.
 *
 * THE ATIS LABEL IS DELIBERATELY NOT THE PUBLISHED CALLSIGN. Norway publishes
 * ENDU's ATIS callsign as "Bardufoss Information", which reads exactly like
 * the AFIS service you would actually talk to at an uncontrolled field - and
 * at Bardufoss there is no AFIS, there is a TWR. So an ATIS row is labelled
 * "<ICAO> ATIS": you do not call an ATIS, you listen to it, and "Information"
 * is reserved for the AFIS service where it means a station answering you.
 * The published callsign is kept in the dataset either way.
 *
 * @param {AirspaceFeature} f
 * @param {{sectors?: AirspaceSector[], at?: [number, number]|null}} [opts]
 * @returns {{tag: string, freqs: string[], callsign: string|null}[]}
 */
export function serviceRows(f, opts) {
  const primary = collectServices(f, SHOWN_SERVICES);
  if (primary.length) return primary;
  return fallbackRows(f, opts).rows;
}

/**
 * The fallback (area control / radio) rows, plus anything that needs saying
 * about how they were chosen.
 *
 * @param {AirspaceFeature} f
 * @param {{sectors?: AirspaceSector[], at?: [number, number]|null}} [opts]
 * @returns {{rows: {tag: string, freqs: string[], callsign: string|null}[], note: string|null}}
 */
function fallbackRows(f, opts) {
  const rows = collectServices(f, FALLBACK_SERVICES);
  const sect = accSectorRows(f, opts);
  if (!sect.rows.length && !sect.note) return { rows, note: null };
  // Replace the single crowded ACC row with one row per resolved sector.
  const others = rows.filter((r) => r.tag !== 'ACC');
  return { rows: sect.rows.concat(others), note: sect.note };
}

/** @param {AirspaceFeature} f @param {string[]} codes
 *  @returns {{tag: string, freqs: string[], callsign: string|null}[]} */
function collectServices(f, codes) {
  /** @type {{tag: string, freqs: string[], callsign: string|null}[]} */
  const rows = [];
  for (const code of codes) {
    /** @type {string[]} */
    const freqs = [];
    /** @type {string|null} */
    let callsign = null;
    for (const sv of f.services || []) {
      if ((sv.code || '').toUpperCase() !== code) continue;
      for (const q of sv.freqs || []) {
        if (isUsableFrequency(q) && !freqs.includes(q.mhz)) freqs.push(q.mhz);
      }
      if (!callsign && sv.callsign) callsign = sv.callsign;
    }
    if (!freqs.length) continue;        // a service with nothing dialable
    rows.push({
      tag: SERVICE_TAGS[code] || code,
      freqs,
      callsign: code === 'ATIS' ? (f.icao ? `${f.icao} ATIS` : 'ATIS') : callsign
    });
  }
  return rows;
}

/**
 * Everything the hover card shows, as structured pieces. The page turns this
 * into markup; this module stays DOM-free.
 *
 * @param {AirspaceFeature} f
 * @param {{sectors?: AirspaceSector[], at?: [number, number]|null}} [opts]
 *        the ACC sector dataset and the cursor position. Needed only for an
 *        airspace that publishes many area-control frequencies - see
 *        accSectorRows for why the position is the question.
 * @returns {{name: string, kindLabel: string, cls: string|null, band: string,
 *            services: {tag: string, freqs: string[], callsign: string|null}[],
 *            notes: string[], color: string}}
 */
export function airspaceInfo(f, opts) {
  const style = airspaceStyle(f.kind);
  const notes = [];
  const primary = collectServices(f, SHOWN_SERVICES);
  const services = primary.length ? primary : [];
  if (!primary.length) {
    const fb = fallbackRows(f, opts);
    services.push(...fb.rows);
    if (fb.note) notes.push(fb.note);
  }
  // A boundary that came from Kartverket rather than the AIP's own coordinate
  // list is worth saying, because it is the one part of the shape the AIP did
  // not state directly.
  if (f.borderSegments) notes.push('boundary follows the national border');
  return {
    name: f.name,
    kindLabel: style.label,
    cls: f.class || null,
    band: limitsText(f),
    services,
    notes,
    color: style.color
  };
}

/**
 * The attribution the overlay must display whenever it is on. Both grants are
 * named because both are load-bearing and they are different: the AIP is used
 * by permission and non-commercially, the border is open data.
 *
 * @param {{attribution?: string, editionLabel?: string, effectiveFrom?: string}|null} dataset
 * @returns {string}
 */
export function airspaceAttribution(dataset) {
  if (!dataset) return '';
  const edition = dataset.editionLabel ? ` ${dataset.editionLabel}` : '';
  const eff = dataset.effectiveFrom ? `, effective ${dataset.effectiveFrom}` : '';
  return `Airspace: AIP Norge${edition}${eff} — © Avinor, used with permission, ` +
    `non-commercial. National border © Kartverket (NLOD). ` +
    `Not for navigation; verify against the current AIP and NOTAM.`;
}

/**
 * Every kind present in a dataset, with a count, for the layer control.
 * @param {AirspaceFeature[]} features
 * @returns {{kind: string, label: string, count: number}[]}
 */
export function airspaceKinds(features) {
  /** @type {Record<string, number>} */
  const counts = {};
  for (const f of features || []) counts[f.kind] = (counts[f.kind] || 0) + 1;
  return Object.keys(counts).sort().map((kind) => ({
    kind, label: airspaceStyle(kind).label, count: counts[kind]
  }));
}
