/**
 * AIP airspace overlay - src/lib/airspace.js (v16.31)
 *
 * The pure half of roadmap item 4: which airspaces to draw for a given
 * viewport, how to colour them, and what to say about one on hover. The
 * Leaflet layers themselves live in the page, with the rest of the map code.
 *
 * DATA: `window.C182_AIP`, generated by tools/build-aip.mjs from the official
 * Avinor eAIP and inlined into both deliveries at the @AIPDATA marker (a
 * file:// page can neither fetch() nor load an ES module). Airspace data is
 * used with permission from Avinor AS, NON-COMMERCIALLY; the national border
 * within it is Kartverket, NLOD. See CLAUDE.md - the non-commercial condition
 * binds the whole project.
 *
 * WHY CULLING IS NOT OPTIONAL: the dataset holds 228 volumes covering all of
 * Norway. Handing every one to Leaflet makes panning unusable, and at country
 * zoom the result is an unreadable wash that hides the CTRs and TMAs a VFR
 * pilot actually needs. So: nothing below MIN_ZOOM, and only what intersects
 * the viewport.
 *
 * WHY HOVER AND NOT CLICK: a click on the map adds a waypoint, and airspace
 * covers most of the map. Making the polygons take clicks would break route
 * building everywhere inside a TMA. Hover carries the information; the click
 * falls through to the map untouched.
 *
 * Pure: no DOM, no Leaflet. The page passes the viewport in and gets plain
 * data back.
 */

/** Nothing is drawn below this zoom: at country zoom 228 polygons are a wash
 *  that buries the airspace that matters. */
export const AIRSPACE_MIN_ZOOM = 7;

/**
 * How each kind is drawn. The fill is deliberately very light - the point of
 * the ICAO chart underneath is that you can read it, and an overlay that
 * obscures the terrain, the MEF figures or the frequencies has made the
 * planner worse.
 *
 * @type {Record<string, {label: string, color: string, dash: string|null}>}
 */
export const AIRSPACE_STYLES = {
  CTR:     { label: 'Control zone',            color: '#2b6cb0', dash: null },
  TIZ:     { label: 'Traffic information zone', color: '#2f855a', dash: null },
  TMA:     { label: 'Terminal control area',   color: '#6b46c1', dash: '6,4' },
  TIA:     { label: 'Traffic information area', color: '#0987a0', dash: '6,4' },
  CTA:     { label: 'Control area',            color: '#4a5568', dash: '2,5' },
  RMZ:     { label: 'Radio mandatory zone',    color: '#c05621', dash: '8,4' },
  TMZ:     { label: 'Transponder mandatory zone', color: '#c05621', dash: '8,4' },
  RMZ_TMZ: { label: 'Radio + transponder mandatory zone', color: '#c05621', dash: '8,4' },
  HTZ:     { label: 'Helicopter traffic zone', color: '#975a16', dash: null },
  ADS:     { label: 'Advisory area',           color: '#975a16', dash: '2,5' }
};

const DEFAULT_STYLE = { label: 'Airspace', color: '#718096', dash: '4,4' };

/** @param {string} kind @returns {{label: string, color: string, dash: string|null}} */
export function airspaceStyle(kind) {
  return AIRSPACE_STYLES[String(kind || '').toUpperCase()] || DEFAULT_STYLE;
}

/**
 * The bounding box of a feature's ring, computed once and cached on it.
 *
 * @param {AirspaceFeature} f
 * @returns {{south: number, west: number, north: number, east: number}}
 */
export function airspaceBounds(f) {
  if (f._bbox) return f._bbox;
  let south = 90, north = -90, west = 180, east = -180;
  for (const [lat, lng] of f.ring) {
    if (lat < south) south = lat;
    if (lat > north) north = lat;
    if (lng < west) west = lng;
    if (lng > east) east = lng;
  }
  f._bbox = { south, west, north, east };
  return f._bbox;
}

/**
 * Which airspaces to draw right now.
 *
 * @param {AirspaceFeature[]} features
 * @param {{south: number, west: number, north: number, east: number}} view
 * @param {number} zoom
 * @param {{kinds?: Record<string, boolean>, minZoom?: number}} [opts]
 *   `kinds` omitted means every kind; a kind mapped to false is hidden.
 * @returns {AirspaceFeature[]}
 */
export function visibleAirspaces(features, view, zoom, opts) {
  const minZoom = opts && typeof opts.minZoom === 'number' ? opts.minZoom : AIRSPACE_MIN_ZOOM;
  if (!(zoom >= minZoom)) return [];
  const kinds = opts && opts.kinds;
  /** @type {AirspaceFeature[]} */
  const out = [];
  for (const f of features || []) {
    if (kinds && kinds[f.kind] === false) continue;
    const b = airspaceBounds(f);
    // bbox overlap; a polygon larger than the viewport still overlaps it
    if (b.south > view.north || b.north < view.south) continue;
    if (b.west > view.east || b.east < view.west) continue;
    out.push(f);
  }
  // Draw the biggest first so a CTR inside a TMA stays clickable-through and
  // visually on top rather than buried under the larger wash.
  out.sort((a, b) => bboxArea(b) - bboxArea(a));
  return out;
}

/** @param {AirspaceFeature} f @returns {number} */
function bboxArea(f) {
  const b = airspaceBounds(f);
  return (b.north - b.south) * (b.east - b.west);
}

/**
 * The published vertical band, as text.
 *
 * NEVER recomputed from a number: the importer keeps GND / UNL / FL as the
 * codes they are, and this only joins what was published. A missing limit
 * shows as `?` rather than being filled in with a plausible altitude.
 *
 * @param {AirspaceFeature} f @returns {string}
 */
export function limitsText(f) {
  const lo = (f.lower && f.lower.text) || '?';
  const hi = (f.upper && f.upper.text) || '?';
  return `${lo} – ${hi}`;
}

/**
 * WHICH FREQUENCIES A VFR PILOT ACTUALLY WANTS, and why the rest are hidden.
 *
 * A published airspace block carries every ATS frequency the aerodrome has.
 * Bardufoss CTR lists twelve, and reciting all twelve buries the three that
 * matter. Shown: ATIS, Approach, Tower, and AFIS (the "Information" service
 * at an AFIS field). Hidden: clearance delivery, surface movement, en-route
 * ACC sectors and non-ATS radio stations - a C182 planning a VFR flight is
 * not calling those.
 *
 * NOTHING IS DISCARDED FROM THE DATA. Every published service and frequency
 * stays in `data/aip.js`; this is the display filter and the AIP remains the
 * reference. There is deliberately no "+N hidden" remark - it was noise.
 */
export const SHOWN_SERVICES = ['ATIS', 'APP', 'TWR', 'AFIS'];

/**
 * Shown ONLY when an airspace has none of the above.
 *
 * Some TMAs have no local approach unit at all - Hammerfest, Helgeland and
 * Lofoten TMA are worked by Polaris Control, and Salen TMA by Salen Control.
 * Hiding the area-control frequency there would leave the card with no one to
 * call for a piece of CONTROLLED airspace, which is worse than one extra row.
 * A CTR that already has TWR and APP never gains a Polaris row.
 */
export const FALLBACK_SERVICES = ['ACC', 'RADIO', 'TFC'];

/** Human tag per service code. @type {Record<string, string>} */
const SERVICE_TAGS = {
  ATIS: 'ATIS', APP: 'APP', TWR: 'TWR', AFIS: 'AFIS',
  ACC: 'ACC', RADIO: 'RADIO', TFC: 'TFC'
};

/**
 * The civil VHF air band, and the reason it - not the source's `MIL` flag -
 * is what keeps military channels out.
 *
 * The eAIP marks SOME military frequencies with a `MIL` remark, but only six
 * in the whole edition: Bardufoss TWR publishes 243.000 with no marker at all.
 * So the band is the real filter (military air is UHF, 225-400 MHz) and the
 * MIL flag is applied on top to catch a military VHF channel.
 */
export const VHF_MIN_MHZ = 118;
export const VHF_MAX_MHZ = 137;

/**
 * Emergency frequencies. Never listed as a working frequency: every pilot
 * knows 121.500, it appears under almost every service, and printing it four
 * times per card crowds out the ones you actually need to dial.
 */
export const GUARD_MHZ = ['121.500', '243.000'];

/** @param {{mhz: string, remarks?: string}} q @returns {boolean} */
export function isUsableFrequency(q) {
  const n = Number(String((q && q.mhz) || '').trim());
  if (!isFinite(n)) return false;
  if (n < VHF_MIN_MHZ || n >= VHF_MAX_MHZ) return false;          // UHF military
  if (/\bMIL\b/i.test(String((q && q.remarks) || ''))) return false;  // flagged military
  if (GUARD_MHZ.includes(String(q.mhz).trim())) return false;      // guard
  return true;
}

/**
 * The service rows for the hover card: tag, frequencies, who you are calling.
 *
 * THE ATIS LABEL IS DELIBERATELY NOT THE PUBLISHED CALLSIGN. Norway publishes
 * ENDU's ATIS callsign as "Bardufoss Information", which reads exactly like
 * the AFIS service you would actually talk to at an uncontrolled field - and
 * at Bardufoss there is no AFIS, there is a TWR. So an ATIS row is labelled
 * "<ICAO> ATIS": you do not call an ATIS, you listen to it, and "Information"
 * is reserved for the AFIS service where it means a station answering you.
 * The published callsign is kept in the dataset either way.
 *
 * @param {AirspaceFeature} f
 * @returns {{tag: string, freqs: string[], callsign: string|null}[]}
 */
export function serviceRows(f) {
  const primary = collectServices(f, SHOWN_SERVICES);
  return primary.length ? primary : collectServices(f, FALLBACK_SERVICES);
}

/** @param {AirspaceFeature} f @param {string[]} codes
 *  @returns {{tag: string, freqs: string[], callsign: string|null}[]} */
function collectServices(f, codes) {
  /** @type {{tag: string, freqs: string[], callsign: string|null}[]} */
  const rows = [];
  for (const code of codes) {
    /** @type {string[]} */
    const freqs = [];
    /** @type {string|null} */
    let callsign = null;
    for (const sv of f.services || []) {
      if ((sv.code || '').toUpperCase() !== code) continue;
      for (const q of sv.freqs || []) {
        if (isUsableFrequency(q) && !freqs.includes(q.mhz)) freqs.push(q.mhz);
      }
      if (!callsign && sv.callsign) callsign = sv.callsign;
    }
    if (!freqs.length) continue;        // a service with nothing dialable
    rows.push({
      tag: SERVICE_TAGS[code] || code,
      freqs,
      callsign: code === 'ATIS' ? (f.icao ? `${f.icao} ATIS` : 'ATIS') : callsign
    });
  }
  return rows;
}

/**
 * Everything the hover card shows, as structured pieces. The page turns this
 * into markup; this module stays DOM-free.
 *
 * @param {AirspaceFeature} f
 * @returns {{name: string, kindLabel: string, cls: string|null, band: string,
 *            services: {tag: string, freqs: string[], callsign: string|null}[],
 *            notes: string[], color: string}}
 */
export function airspaceInfo(f) {
  const style = airspaceStyle(f.kind);
  const notes = [];
  // A boundary that came from Kartverket rather than the AIP's own coordinate
  // list is worth saying, because it is the one part of the shape the AIP did
  // not state directly.
  if (f.borderSegments) notes.push('boundary follows the national border');
  return {
    name: f.name,
    kindLabel: style.label,
    cls: f.class || null,
    band: limitsText(f),
    services: serviceRows(f),
    notes,
    color: style.color
  };
}

/**
 * The attribution the overlay must display whenever it is on. Both grants are
 * named because both are load-bearing and they are different: the AIP is used
 * by permission and non-commercially, the border is open data.
 *
 * @param {{attribution?: string, editionLabel?: string, effectiveFrom?: string}|null} dataset
 * @returns {string}
 */
export function airspaceAttribution(dataset) {
  if (!dataset) return '';
  const edition = dataset.editionLabel ? ` ${dataset.editionLabel}` : '';
  const eff = dataset.effectiveFrom ? `, effective ${dataset.effectiveFrom}` : '';
  return `Airspace: AIP Norge${edition}${eff} — © Avinor, used with permission, ` +
    `non-commercial. National border © Kartverket (NLOD). ` +
    `Not for navigation; verify against the current AIP and NOTAM.`;
}

/**
 * Every kind present in a dataset, with a count, for the layer control.
 * @param {AirspaceFeature[]} features
 * @returns {{kind: string, label: string, count: number}[]}
 */
export function airspaceKinds(features) {
  /** @type {Record<string, number>} */
  const counts = {};
  for (const f of features || []) counts[f.kind] = (counts[f.kind] || 0) + 1;
  return Object.keys(counts).sort().map((kind) => ({
    kind, label: airspaceStyle(kind).label, count: counts[kind]
  }));
}
