#!/usr/bin/env node
/**
 * Build: src/ -> dist/C182_FlightPlanner.html
 *
 * Produces ONE self-contained HTML file that is opened by double-clicking
 * (no server, no install, works offline). Bulk datasets may still ship as
 * optional classic-script sidecars in data/ next to the file.
 *
 * The bundle is emitted as a CLASSIC script (esbuild --format=iife) and
 * inlined at the @BUNDLE marker, above the app's main script block: a
 * page opened from file:// cannot load ES modules (the browser blocks
 * them cross-origin) but runs classic scripts fine. Verified in Chromium.
 *
 * The build also enforces the project's ship checklist, so a broken
 * artifact can never reach dist/:
 *   - the bundle and the page script must both parse
 *   - no duplicate DOM ids
 *   - APP_VERSION must match package.json
 *   - the marker must actually have been replaced
 *
 *   node tools/build.mjs [--watch]
 */
import { build as esbuild } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_HTML = join(ROOT, 'src', 'index.html');
const ENTRY = join(ROOT, 'src', 'main.js');
const OUT_DIR = join(ROOT, 'dist');
const OUT_HTML = join(OUT_DIR, 'C182_FlightPlanner.html');
const MARKER = /^[ \t]*<!-- @BUNDLE:.*-->[ \t]*\n/m;

const fail = (msg) => { console.error('BUILD FAILED: ' + msg); process.exit(1); };

async function bundle() {
  const result = await esbuild({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'iife',          // classic script: required for file:// pages
    target: 'es2019',
    charset: 'utf8',
    legalComments: 'inline',
    write: false,
    logLevel: 'warning'
  });
  return result.outputFiles[0].text;
}

function scriptBlocks(html) {
  return [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
}

function checkSyntax(code, label) {
  try {
    execFileSync(process.execPath, ['--check', '-'], { input: code, stdio: ['pipe', 'pipe', 'pipe'] });
  } catch (e) {
    fail(label + ' does not parse:\n' + String(e.stderr || e.message).split('\n').slice(0, 6).join('\n'));
  }
}

function checkDuplicateIds(html) {
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
  const dupes = [...new Set(ids.filter((v, i, a) => a.indexOf(v) !== i))];
  if (dupes.length) fail('duplicate DOM ids: ' + dupes.join(', '));
}

function checkVersion(html) {
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
  const m = html.match(/const APP_VERSION = '([^']+)'/);
  if (!m) fail('APP_VERSION not found in the page');
  const norm = (v) => String(v).split('.').slice(0, 2).join('.');
  if (norm(m[1]) !== norm(pkg)) {
    fail(`APP_VERSION ${m[1]} does not match package.json ${pkg} - a release bumps both.`);
  }
  return m[1];
}

export async function runBuild({ quiet = false } = {}) {
  const srcHtml = readFileSync(SRC_HTML, 'utf8');
  if (!MARKER.test(srcHtml)) fail('src/index.html has no @BUNDLE marker');

  const code = await bundle();
  checkSyntax(code, 'bundle (src/main.js)');

  // The bundle is inserted verbatim; guard the one sequence that could
  // terminate the host <script> element early.
  if (/<\/script/i.test(code)) fail('bundle contains a literal </script sequence');

  const banner = '  <!-- GENERATED by tools/build.mjs from src/ - do not edit this file; edit src/ and rebuild. -->\n';
  const html = srcHtml.replace(MARKER, banner + '  <script>\n' + code + '  </script>\n');
  if (MARKER.test(html)) fail('marker was not replaced');

  const blocks = scriptBlocks(html);
  checkSyntax(blocks[blocks.length - 1], 'page script (src/index.html)');
  checkDuplicateIds(html);
  const version = checkVersion(html);

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_HTML, html);
  if (!quiet) {
    console.log(`built dist/C182_FlightPlanner.html  v${version}  ` +
      `${(html.length / 1024).toFixed(0)} KB (bundle ${(code.length / 1024).toFixed(1)} KB, ` +
      `${blocks.length} script blocks) - checks passed`);
  }
  return OUT_HTML;
}

if (process.argv[1] && process.argv[1].endsWith('build.mjs')) {
  await runBuild();
  if (process.argv.includes('--watch')) {
    const { watch } = await import('node:fs');
    console.log('watching src/ ...');
    let t = null;
    for (const target of ['src', 'src/lib']) {
      watch(join(ROOT, target), () => {
        clearTimeout(t);
        t = setTimeout(() => runBuild().catch(e => console.error(e.message)), 120);
      });
    }
  }
}
